### PR TITLE
Add financial support translation for ID (Bahasa Indonesia)

### PR DESCRIPTION
**Pull request by muslih**
## Description 
Add translation for the financial support section for ID (Bahasa Indonesia)

## Preview
image

### CODE REVIEW

**Comment by alex-w** [comment]
Please use Transifex to translate the website - https://app.transifex.com/stellarium/stellarium/translate/#id/stellarium-github-io/126380693

**Comment by muslih** [comment]
I am unable to open URL above  @alex-w 
image

**Comment by gzotti** [comment]
Worked for me. Are you registered on Transifex?

**Comment by muslih** [comment]
@gzotti No, I haven't. I have no access on Transifex :pray:

**Comment by gzotti** [comment]
Let me guess: register on Transifex to become Stellarium translator, and the link should work.

**Comment by muslih** [comment]
> register on Transifex to become Stellarium translator,

Yeah @gzotti, I did it and now on pending state,  seems need approval from the team 

image

**Comment by muslih** [comment]
Just registered on Transifex @alex-w  @gzotti  :bow: 

https://app.transifex.com/stellarium/stellarium/translate/#id/stellarium-github-io/439148964?q=text%3Afinancial

**Pull request closed without merging**
